### ISSUE TITLE
PyPi support

### ISSUE THREAD

**Issue by mmingle** [shymonk/django-datatable#20]
Amazing module I love it, and extremely well documented. My only dislike is that it needs to be added to PyPi so we can pip install django-datatable

**Comment by shymonk** [comment]
First of all, Thanks for your suggestion.
In fact i have tried to submit django-datatable to pypi server fewer months ago, but failed due to a existed and spam package (https://pypi.python.org/pypi/django-datatable).

I am about to contact with package owner to rewrite the package for your convenience.

**Comment by shymonk** [comment]
https://pypi.python.org/pypi/django-datatable/0.1.5
